[package]
name = "screen-test"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.9.5"
gdk4 = "0.9.5"
glib = "0.20.7"
gio = "0.20.7"
